// <auto-generated />
using System;
using FIMS2.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIMS2.Migrations
{
    [DbContext(typeof(FIMSContext))]
    [Migration("20240321235107_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("FIMS2.Models.CustomerAllocation", b =>
                {
                    b.Property<int>("AllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("AllocationID");

                    b.HasIndex("LotNumber");

                    b.ToTable("CustomerAllocations");
                });

            modelBuilder.Entity("FIMS2.Models.Lot", b =>
                {
                    b.Property<string>("LotNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("LotNumber");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("FIMS2.Models.CustomerAllocation", b =>
                {
                    b.HasOne("FIMS2.Models.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });
#pragma warning restore 612, 618
        }
    }
}
